
#spring
spring:
  datasource:
    name: subike
    url: jdbc:mysql://127.0.0.1:3306/subike
    username: root
    password: root

  #activemq
  activemq:
    borker-url: tcp://127.0.0.1:61616
    pool:
      enabled: false
logging:
  config: classpath:logback.xml
#reids
redis:
  host: 127.0.0.1
  port: 6379
  auth:
  max-idle: 5
  max-total: 10
  max-wait-millis: 3000